# Generated by Django 3.0.8 on 2020-08-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilhao', '0002_auto_20200828_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='multifuncional',
            name='ampliacao_e_reducao',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='multifuncional',
            name='bandeja_multiuso2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='multifuncional',
            name='compatibilidade',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='multifuncional',
            name='copias_multiplas',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='multifuncional',
            name='destino_de_saida',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='multifuncional',
            name='formatos_de_saida',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='multifuncional',
            name='tamanho_do_adf',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='multifuncional',
            name='tamanho_do_vidro',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='multifuncional',
            name='tipo_da_passagem_do_adf',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='multifuncional',
            name='velocidade_de_digitacao',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
