# Generated by Django 3.0.8 on 2020-08-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilhao', '0003_auto_20200828_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='multifuncional',
            name='bandeja_de_entrada_de_papel2',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
