# Generated by Django 3.0.8 on 2020-08-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilhao', '0004_multifuncional_bandeja_de_entrada_de_papel2'),
    ]

    operations = [
        migrations.AddField(
            model_name='multifuncional',
            name='resolucao2',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
