# Generated by Django 3.0.8 on 2020-08-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilhao', '0011_auto_20200828_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impressora',
            name='bandeja_de_entrada_de_papel',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='bandeja_de_saida',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='bandeja_multiuso',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='capacidade_maxima_de_bandejas',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='ciclo_mensal',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='disco_rigido',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='fabricante',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='frente_e_verso_automatico',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='gramatura_na_bandeja_multiuso',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='gramatura_na_bandeja_principal',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='interface_opcional',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='interface_padrao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='interface_wireless',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='linguagem_de_impressao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='memoria_minima',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='modelo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='painel',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='processador',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='resolucao_de_impressao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='sistema_operacional',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='suporta_tamanho',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='tecnologia_de_impressao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='tempo_de_primeira_pagina',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='impressora',
            name='velocidade_de_impressao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='ampliacao_e_reducao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='bandeja_de_entrada_de_papel',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='bandeja_de_entrada_de_papel2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='bandeja_de_saida',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='bandeja_multiuso',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='bandeja_multiuso2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='capacidade_de_folhas_no_adf',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='capacidade_maxima_de_bandejas',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='capacidade_maxima_de_bandejas_opcional',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='ciclo_mensal',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='compatibilidade',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='copias_multiplas',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='destino_de_saida',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='disco_rigido',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='fabricante',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='formatos_de_saida',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='frente_e_verso_automatico',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='gramatura_na_bandeja_multiuso',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='gramatura_na_bandeja_principal',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='interface_opcional',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='interface_padrao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='interface_wireless',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='linguagem_de_impressao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='memoria_de_fax',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='memoria_minima',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='modelo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='painel',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='processador',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='resolucao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='resolucao2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='resolucao_de_impressao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='sistema_operacional',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='suporta_tamanho',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='tamanho_do_adf',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='tamanho_do_vidro',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='tecnologia_de_impressao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='tempo_de_primeira_pagina',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='tipo_da_passagem_do_adf',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='velocidade_de_digitacao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='velocidade_de_fax',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional',
            name='velocidade_de_impressao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional_producao',
            name='ampliacao_e_reducao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional_producao',
            name='bandeja_de_entrada_de_papel',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional_producao',
            name='bandeja_de_saida',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional_producao',
            name='bandeja_multiuso',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional_producao',
            name='capacidade_maxima_de_bandejas',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional_producao',
            name='ciclo_mensal',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional_producao',
            name='compatibilidade',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional_producao',
            name='copias_multiplas',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional_producao',
            name='destino_de_saida',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional_producao',
            name='disco_rigido',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional_producao',
            name='fabricante',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional_producao',
            name='formatos_de_saida',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional_producao',
            name='frente_e_verso_automatico',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional_producao',
            name='gramatura_na_bandeja_multiuso',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional_producao',
            name='gramatura_na_bandeja_principal',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional_producao',
            name='interface_opcional',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional_producao',
            name='interface_padrao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional_producao',
            name='interface_wireless',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional_producao',
            name='linguagem_de_impressao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional_producao',
            name='memoria_minima',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional_producao',
            name='modelo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional_producao',
            name='painel',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional_producao',
            name='processador',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional_producao',
            name='resolucao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional_producao',
            name='resolucao_de_copia',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional_producao',
            name='resolucao_de_impressao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional_producao',
            name='sistema_operacional',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional_producao',
            name='suporta_tamanho',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional_producao',
            name='tamanho_do_adf',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional_producao',
            name='tamanho_do_vidro',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional_producao',
            name='tecnologia_de_impressao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional_producao',
            name='tempo_de_primeira_pagina',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional_producao',
            name='tempo_de_primeira_pagina_copia',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional_producao',
            name='tipo_da_passagem_do_adf',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional_producao',
            name='velocidade_de_copia',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional_producao',
            name='velocidade_de_digitacao',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='multifuncional_producao',
            name='velocidade_de_impressao',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
