# Generated by Django 3.0.8 on 2020-08-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilhao', '0013_auto_20200828_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='multifuncional_producao',
            name='capacidade_de_folhas_no_adf',
            field=models.TextField(blank=True),
        ),
    ]
