# Generated by Django 3.0.8 on 2020-08-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilhao', '0014_multifuncional_producao_capacidade_de_folhas_no_adf'),
    ]

    operations = [
        migrations.AddField(
            model_name='multifuncional_producao',
            name='capacidade_maxima_de_bandejas_opcional',
            field=models.TextField(blank=True),
        ),
    ]
