# Generated by Django 3.0.8 on 2020-08-28 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planilhao', '0016_multifuncional_producao_bandeja_multiuso2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multifuncional_producao',
            name='bandeja_multiuso2',
        ),
        migrations.RemoveField(
            model_name='multifuncional_producao',
            name='capacidade_maxima_de_bandejas_opcional',
        ),
    ]
