# Generated by Django 3.0.8 on 2020-08-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilhao', '0018_remove_multifuncional_producao_tempo_de_primeira_pagina_copia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impressora',
            name='a3',
        ),
        migrations.RemoveField(
            model_name='impressora',
            name='a4',
        ),
        migrations.RemoveField(
            model_name='impressora',
            name='colorida',
        ),
        migrations.RemoveField(
            model_name='multifuncional',
            name='a3',
        ),
        migrations.RemoveField(
            model_name='multifuncional',
            name='a4',
        ),
        migrations.RemoveField(
            model_name='multifuncional',
            name='colorida',
        ),
        migrations.RemoveField(
            model_name='multifuncional_producao',
            name='a3',
        ),
        migrations.RemoveField(
            model_name='multifuncional_producao',
            name='a4',
        ),
        migrations.RemoveField(
            model_name='multifuncional_producao',
            name='colorida',
        ),
        migrations.AddField(
            model_name='impressora',
            name='tamanho_papel',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='impressora',
            name='tinta',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='multifuncional',
            name='tamanho_papel',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='multifuncional',
            name='tinta',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='multifuncional_producao',
            name='tamanho_papel',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='multifuncional_producao',
            name='tinta',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
