# Generated by Django 3.0.8 on 2020-08-28 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planilhao', '0019_auto_20200828_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impressora',
            name='tamanho_papel',
        ),
        migrations.RemoveField(
            model_name='multifuncional',
            name='tamanho_papel',
        ),
        migrations.RemoveField(
            model_name='multifuncional_producao',
            name='tamanho_papel',
        ),
    ]
