INSERT INTO planilhao.planilhao_multifuncional_producao
(uploaded_at,fabricante,modelo,tecnologia_de_impressao,velocidade_de_impressao,processador,memoria_minima,disco_rigido,interface_padrao,interface_opcional,interface_wireless,resolucao_de_impressao,ciclo_mensal,linguagem_de_impressao,frente_e_verso_automatico,sistema_operacional,painel,velocidade_de_copia,tempo_de_primeira_pagina,resolucao_de_copia,ampliacao_e_reducao,copias_multiplas,velocidade_de_digitacao,compatibilidade,resolucao,destino_de_saida,formatos_de_saida,tamanho_do_vidro,tamanho_do_adf,tipo_da_passagem_do_adf,capacidade_de_folhas_no_adf,bandeja_de_entrada_de_papel,capacidade_maxima_de_bandejas,bandeja_multiuso,bandeja_de_saida,suporta_tamanho,gramatura_na_bandeja_principal,gramatura_na_bandeja_multiuso,colorida,a4,a3,foto,catalogo)
VALUES('2020-08-26 13:31:00','Xerox ','Xerox D95A','Não informado','100  ppm – A4','Não informado','2 GB RAM - Servidor de cópia/impressão integrado','250 GB Hard Disk Drive - Servidor de cópia/impressão integrado',' Ethernet interface (10 MBTX/sec, 100 MBTX/sec and 1000MBTX/sec)- Servidor de cópia/impressão integrado','Não possui ','Não possui ','Resolução RIP até 1200 x 1200 dpi e resolução até 2400 x 2400 dpi','2.000.000 páginas por mês','Adobe® PostScript® Níveis 1, 2, 3
• Adobe PDF
• PDF/X-1a, 3, e 4
• Encapsulated PostScript (EPS)
• Enhanced PCL® 6/PCL 5
• Formatos de documento do MS Office: doc, xls, ppt, pub (via Pastas ativas) - Servidor de Impressão','Impressão de uma ou duas faces','Microsoft Windows 7
Microsoft Windows 2000,
Microsoft Windows XP,
Microsoft Windows Server 2003,
Microsoft Windows Vista
PostScript:
Microsoft Windows 2000,
Microsoft Windows XP,
Microsoft Windows Server 2003,
Microsoft Windows Vista,
Mac OS 7.5 ou superior
Mac OS 8x, 9x
Mac OS X 10.x',' uma grande tela touchscreen colorida','Velocidade de cópia
contínua 7 x 10 pol./B5: 95 folhas/min','3 segundos','Resolução de digitalizaç- 600 × 600 dpi / Resolução de saída 600 × 600 dpi','% Variável: 1:0.25 a 1:4.00 (em incrementos de 1%)','9.999 folhas','200 ipm','TWAIN','600 x 600 dpi','• Scan to Email com notifi cação de entrega de e-mail
• Scan to Network File Server',' PDF, JPEG, TIFF ou TIFF de várias páginas;
suporta LDAP','A5 a A3','A5 a A3','Alimentador automático de documentos duplex','250 folhas','Bandeja 1*: 1100 folhas – A4
• Bandeja 2*: 1600 folhas – A4
• Bandejas 3-4*: 550 folhas cada uma ',' Alimentador de alta capacidade opcional: 2 bandejas, 2000 folhas cada /  Opcional Alimentador de alta capacidade com 1 bandeja para formatos maiores: 2 000 folhas / Opcional Alimentador de alta capacidade com 2 bandejas para formatos maiores: 4 000 folhas','250 folhas','Capacidade do empilhador: 3000 folhas','A3, A4, 8,5 x 11','52 g/m² a 216 g/m²','52 g/m² até 253 g/m²',0,1,1,'', '');

INSERT INTO planilhao.planilhao_multifuncional_producao
(uploaded_at,fabricante,modelo,tecnologia_de_impressao,velocidade_de_impressao,processador,memoria_minima,disco_rigido,interface_padrao,interface_opcional,interface_wireless,resolucao_de_impressao,ciclo_mensal,linguagem_de_impressao,frente_e_verso_automatico,sistema_operacional,painel,velocidade_de_copia,tempo_de_primeira_pagina,resolucao_de_copia,ampliacao_e_reducao,copias_multiplas,velocidade_de_digitacao,compatibilidade,resolucao,destino_de_saida,formatos_de_saida,tamanho_do_vidro,tamanho_do_adf,tipo_da_passagem_do_adf,capacidade_de_folhas_no_adf,bandeja_de_entrada_de_papel,capacidade_maxima_de_bandejas,bandeja_multiuso,bandeja_de_saida,suporta_tamanho,gramatura_na_bandeja_principal,gramatura_na_bandeja_multiuso,colorida,a4,a3,foto,catalogo)
VALUES('2020-08-26 13:31:01','Xerox ','Xerox PrimeLink B9100','Não informado','100  ppm – 8,5 x 11 pol. (A4)','Dual Core de 1,6 GHz - Servidor integrado Xerox',' RAM de 4 GB  - Servidor integrado Xerox','Disco rígido de 320 GB ou mais com 14,6 GB para armazenamento de documentos','10/100/1000 MB/s padrão - Servidor integrado Xerox','Não possui ','Não possui ','Resolução RIP de até 1200 x 1200 dpi e resolução de impressão de até 2400 x 2400 dpi','3,0 milhões de páginas','PDF, XPS®, PCL® 6, HP-GL2 (envio direto),
TIFF, JPEG
• Adobe® PostScript® 3™ ','Impressão só frente ou frente e verso','Windows / Mac OS / Unix e Linux / Citrix / Novell - Servidor integrado Xerox','Visor do painel plano com tela de
seleção por toque colorida de 10,4 pol - Servidor integrado Xerox','A4: 210 x 297 mm; A: 8,5 x 11 pol.: 1 Face: 100 ppm;','3,5 segundos ou menos','Resolução de digitalização 600 x 600 dpi, 400 x 400 dpi, 300 x 300 dpi, 200 x 200 dpi / Resolução de saída 600 x 600 dpi','100%: 1:1 ± 0,7%
% de Pré-ajuste: 1:0,500, 1:0,707, 1:0,816, 1:0,866, 1:1,154,1:1,225,
1:1,414, 1:1,632, 1:2,000
% variável: 1:0,25 a 1:4,00 em incrementos de 1%','9999 folhas','270 ipm','TWAIN - Servidor integrado Xerox','600 x 600 dpi','Digitalizar para E-mail, com notificação de entrega de e-mail
• Digitalizar para Servidor de arquivos de rede','PDF, JPEG, TIFF ou TIFF de várias páginas; suporta LDAP','Máximo: A3: 297 x 420 mm / Mínimo: A5: 148 x 210 mm','Não informado','Alimentador automático de originais em frente e verso de única passagem','250 folhas','• Bandeja 1: 1.100 folhas / • Bandeja 2: 1.600 folhas / Bandeja 3-4: 550 folhas cada ','Alimentador de alta capacidade opcional: Duas bandejas, 4.000 folhas / Alimentador de alta capacidade superdimensionado de uma bandeja opcional (não disponível com a Xerox® B9136): 2.000 folhas','250 folhas','Bandeja de coleta única para até 500 folhas (opcional - apenas B9100)','A3: A4: A5:','52 - 216 g/m²','52 a 350 g/m²',0,1,1,'', '');

INSERT INTO planilhao.planilhao_multifuncional_producao
(uploaded_at,fabricante,modelo,tecnologia_de_impressao,velocidade_de_impressao,processador,memoria_minima,disco_rigido,interface_padrao,interface_opcional,interface_wireless,resolucao_de_impressao,ciclo_mensal,linguagem_de_impressao,frente_e_verso_automatico,sistema_operacional,painel,velocidade_de_copia,tempo_de_primeira_pagina,resolucao_de_copia,ampliacao_e_reducao,copias_multiplas,velocidade_de_digitacao,compatibilidade,resolucao,destino_de_saida,formatos_de_saida,tamanho_do_vidro,tamanho_do_adf,tipo_da_passagem_do_adf,capacidade_de_folhas_no_adf,bandeja_de_entrada_de_papel,capacidade_maxima_de_bandejas,bandeja_multiuso,bandeja_de_saida,suporta_tamanho,gramatura_na_bandeja_principal,gramatura_na_bandeja_multiuso,colorida,a4,a3,foto,catalogo)
VALUES('2020-08-26 13:31:02','Ricoh ','Ricoh Pro 8310s','Laser','111 ppm','1.91 GHz','2 GB','640 GB','Ethernet (1000BASE-T/100BASE-TX/10Base-T); USB 2.0','IEEE802.11a/b/g/n, Bluetooth','Opcional IEEE802.11a/b/g/n','VCSEL: 2400 x 4800 dpi
Impressão: 1200 x 1200 dpi','1000K','PCL 5e, PCL 6, PDF, JPEG, TIFF
PDL Opcional Adobe PostScript 3, IPDS','frente e o verso','Windows, Mac OS X 10.11 ou
posterior, NetWare 6.5, UNIX Sun Solaris 10, HP-UX 11.x/11i v2/11i v3, SCO OpenServer 5.0.7/6.0, RedHat Linux','Painel de Operação Inteligente Sensível ao Toque, Colorido, de 17 ','111 ppm','5,6 segundos','VCSEL: 2400 × 4800 ppp
Cópia: 1200 × 1200 ppp','Auto Redução/Ampliação','Não informado','Simplex: 120 ipm; Duplex: 220 ipm','TWAIN','100/150/200/300/400/600 dpi','Digitalizar para USB/SD, Digitalizar para Email/Pasta/SMB/FTP/ URL
/PDF/A','Página Única: TIFF/JPEG/PDF/PDF de Alta
Compressão Diversas Páginas: TIFF/PDF/PDF de Alta
Compressão','297 × 432 mm','Não informado','digitalização duplex colorida, em passada única','220 folhas','Bandeja 1: 2200 folhas (1100 × 2)
Bandejas 2 e 3: 1100 folhas (550 × 2)','Capacidade máxima de papel de 12.600 folhas','Opcional Bandeja de Alimentação Manual BY5020 - 500 folhas','Não informado','Carta, A5/meio-Carta (140 x 216 mm) a 330 x 457 mm','52 a 256 g/m²','52 a 216 g/m²',0,1,1,'', '');

INSERT INTO planilhao.planilhao_multifuncional_producao
(uploaded_at,fabricante,modelo,tecnologia_de_impressao,velocidade_de_impressao,processador,memoria_minima,disco_rigido,interface_padrao,interface_opcional,interface_wireless,resolucao_de_impressao,ciclo_mensal,linguagem_de_impressao,frente_e_verso_automatico,sistema_operacional,painel,velocidade_de_copia,tempo_de_primeira_pagina,resolucao_de_copia,ampliacao_e_reducao,copias_multiplas,velocidade_de_digitacao,compatibilidade,resolucao,destino_de_saida,formatos_de_saida,tamanho_do_vidro,tamanho_do_adf,tipo_da_passagem_do_adf,capacidade_de_folhas_no_adf,bandeja_de_entrada_de_papel,capacidade_maxima_de_bandejas,bandeja_multiuso,bandeja_de_saida,suporta_tamanho,gramatura_na_bandeja_principal,gramatura_na_bandeja_multiuso,colorida,a4,a3,foto,catalogo)
VALUES('2020-08-26 13:31:03','Canon ','Canon VARIOPRINT 115 ','DirectPress','Velocidade de impressão máxima (ipm/ppm):115 (A4/Carta)','2,7 GHz','4 GB','500 GB','Não informado','Não possui ','Não possui ','600 x 2400 dpi, 200 lpi','800.000 impressões','PCL: Adobe® PostScript® 3:','frente e verso automático','Windows / Mac / Linux ','Não informado','Não informado','3,9 Segundos','Até 600 x 600 dpi','Não informado','Não informado','Até 120 ipm','Não informado','Até 600 x 600 dpi','Digitalizar para SMB, Digitalizar para FTP, Digitalizar para USB, Digitalizar para E-mail, Digitalizar para DocBox','Não informado','Não informado','Statement até 279,4 mm x 431,8 mm','Duplex','300 Folhas','4.000 folhas (80 g/m2) / 2 Bandejas de Volume: 1.500 folhas','(Módulo de Entrada de Papel Externo) (Opcional) Bandeja 1 e 2: 600 folhas, Bandeja 3 e 4: 1.700 folhas / 4.600 Folhas','Não informado','250 folhas','Máximo: 320 mm x 487 mm','50 g/m2 a 300 g/m2','50 g/m2 a 300 g/m2',0,1,1,'', '');

INSERT INTO planilhao.planilhao_multifuncional_producao
(uploaded_at,fabricante,modelo,tecnologia_de_impressao,velocidade_de_impressao,processador,memoria_minima,disco_rigido,interface_padrao,interface_opcional,interface_wireless,resolucao_de_impressao,ciclo_mensal,linguagem_de_impressao,frente_e_verso_automatico,sistema_operacional,painel,velocidade_de_copia,tempo_de_primeira_pagina,resolucao_de_copia,ampliacao_e_reducao,copias_multiplas,velocidade_de_digitacao,compatibilidade,resolucao,destino_de_saida,formatos_de_saida,tamanho_do_vidro,tamanho_do_adf,tipo_da_passagem_do_adf,capacidade_de_folhas_no_adf,bandeja_de_entrada_de_papel,capacidade_maxima_de_bandejas,bandeja_multiuso,bandeja_de_saida,suporta_tamanho,gramatura_na_bandeja_principal,gramatura_na_bandeja_multiuso,colorida,a4,a3,foto,catalogo)
VALUES('2020-08-26 13:31:04','Xerox ','Xerox D125','Não informado','125 ppm – A4','Não informado','2 GB RAM - Servidor de cópia/impressão integrado','250 GB Hard Disk Drive - Servidor de cópia/impressão integrado',' Ethernet interface (10 MBTX/sec, 100 MBTX/sec and 1000MBTX/sec)- Servidor de cópia/impressão integrado','Não possui ','Não possui ','Resolução RIP até 1200 x 1200 dpi e resolução até 2400 x 2400 dpi','2.000.000 páginas por mês','Adobe® PostScript® Níveis 1, 2, 3
• Adobe PDF
• PDF/X-1a, 3, e 4
• Encapsulated PostScript (EPS)
• Enhanced PCL® 6/PCL 5
• Formatos de documento do MS Office: doc, xls, ppt, pub (via Pastas ativas) - Servidor de Impressão','Impressão de uma ou duas faces','Windows / Mac OS / Citrix / Custom driver for Unix: / Oracle Solaris® / Linux® Fedora Core 1/5 / Red Hat / Citrix and WHQL certification*','10.4-inch colour, touchscreen
flat-panel display','7 x 10 pol./B5: 116 folhas/min
8,5 x 11 pol./A4: 110 folhas/min','3 segundos','Resolução de digitalizaç- 600 × 600 dpi / Resolução de saída 600 × 600 dpi','% Variável: 1:0.25 a 1:4.00 (em incrementos de 1%)','9.999 folhas','200 ipm','TWAIN','600 x 600 dpi','• Scan to Email com notifi cação de entrega de e-mail
• Scan to Network File Server',' PDF, JPEG, TIFF ou TIFF de várias páginas;
suporta LDAP','A5 a A3','A5 a A3','Alimentador automático de documentos duplex','250 folhas','Bandeja 1*: 1100 folhas – A4
• Bandeja 2*: 1600 folhas – A4
• Bandejas 3-4*: 550 folhas cada uma ',' Alimentador de alta capacidade opcional: 2 bandejas, 2000 folhas cada /  Opcional Alimentador de alta capacidade com 1 bandeja para formatos maiores: 2 000 folhas / Opcional Alimentador de alta capacidade com 2 bandejas para formatos maiores: 4 000 folhas','250 folhas','Capacidade do empilhador: 3000 folhas','A3, A4, 8,5 x 11','52 g/m² a 216 g/m²','52 g/m² até 253 g/m²',0,1,1,'', '');

INSERT INTO planilhao.planilhao_multifuncional_producao
(uploaded_at,fabricante,modelo,tecnologia_de_impressao,velocidade_de_impressao,processador,memoria_minima,disco_rigido,interface_padrao,interface_opcional,interface_wireless,resolucao_de_impressao,ciclo_mensal,linguagem_de_impressao,frente_e_verso_automatico,sistema_operacional,painel,velocidade_de_copia,tempo_de_primeira_pagina,resolucao_de_copia,ampliacao_e_reducao,copias_multiplas,velocidade_de_digitacao,compatibilidade,resolucao,destino_de_saida,formatos_de_saida,tamanho_do_vidro,tamanho_do_adf,tipo_da_passagem_do_adf,capacidade_de_folhas_no_adf,bandeja_de_entrada_de_papel,capacidade_maxima_de_bandejas,bandeja_multiuso,bandeja_de_saida,suporta_tamanho,gramatura_na_bandeja_principal,gramatura_na_bandeja_multiuso,colorida,a4,a3,foto,catalogo)
VALUES('2020-08-26 13:31:05','Xerox ','Xerox PrimeLink B9125','Não informado','125 ppm – 8,5 x 11 pol. (A4)','Dual Core de 1,6 GHz - Servidor integrado Xerox',' RAM de 4 GB  - Servidor integrado Xerox','Disco rígido de 320 GB ou mais com 14,6 GB para armazenamento de documentos','10/100/1000 MB/s padrão - Servidor integrado Xerox','Não possui ','Não possui ','Resolução RIP de até 1200 x 1200 dpi e resolução de impressão de até 2400 x 2400 dpi','3,0 milhões de páginas','PDF, XPS®, PCL® 6, HP-GL2 (envio direto), TIFF, JPEG
• Adobe® PostScript® 3™ ','Impressão só frente ou frente e verso','Windows / Mac OS / Unix e Linux / Citrix / Novell - Servidor integrado Xerox','Visor do painel plano com tela de seleção por toque colorida de 10,4 pol - Servidor integrado Xerox','A4: 210 x 297 mm; A: 8,5 x 11 pol.: 1 Face: 125 ppm','3,5 segundos ou menos','Resolução de digitalização 600 x 600 dpi, 400 x 400 dpi, 300 x 300 dpi, 200 x 200 dpi / Resolução de saída 600 x 600 dpi','100%: 1:1 ± 0,7%
% de Pré-ajuste: 1:0,500, 1:0,707, 1:0,816, 1:0,866, 1:1,154,1:1,225,
1:1,414, 1:1,632, 1:2,000
% variável: 1:0,25 a 1:4,00 em incrementos de 1%','9999 folhas','270 ipm','TWAIN - Servidor integrado Xerox','600 x 600 dpi','Digitalizar para E-mail, com notificação de entrega de e-mail
• Digitalizar para Servidor de arquivos de rede','PDF, JPEG, TIFF ou TIFF de várias páginas; suporta LDAP','Máximo: A3: 297 x 420 mm / Mínimo: A5: 148 x 210 mm','Não informado','Alimentador automático de originais em frente e verso de única passagem','250 folhas','• Bandeja 1: 1.100 folhas / • Bandeja 2: 1.600 folhas / Bandeja 3-4: 550 folhas cada ','Alimentador de alta capacidade opcional: Duas bandejas, 4.000 folhas / Alimentador de alta capacidade superdimensionado de duas bandejas opcional (não disponível com a Xerox® B9100): 4.000 folhas','250 folhas','Não informado','A3: A4: A5:','52 - 216 g/m²','52 a 350 g/m²',0,1,1,'', '');

INSERT INTO planilhao.planilhao_multifuncional_producao
(uploaded_at,fabricante,modelo,tecnologia_de_impressao,velocidade_de_impressao,processador,memoria_minima,disco_rigido,interface_padrao,interface_opcional,interface_wireless,resolucao_de_impressao,ciclo_mensal,linguagem_de_impressao,frente_e_verso_automatico,sistema_operacional,painel,velocidade_de_copia,tempo_de_primeira_pagina,resolucao_de_copia,ampliacao_e_reducao,copias_multiplas,velocidade_de_digitacao,compatibilidade,resolucao,destino_de_saida,formatos_de_saida,tamanho_do_vidro,tamanho_do_adf,tipo_da_passagem_do_adf,capacidade_de_folhas_no_adf,bandeja_de_entrada_de_papel,capacidade_maxima_de_bandejas,bandeja_multiuso,bandeja_de_saida,suporta_tamanho,gramatura_na_bandeja_principal,gramatura_na_bandeja_multiuso,colorida,a4,a3,foto,catalogo)
VALUES('2020-08-26 13:31:07','Canon ','Canon varioPRINT 130','DirectPress','Velocidade de impressão máxima (ipm/ppm): 130 (A4/Carta)','2,7 GHz','4 GB','500 GB','Não informado','Não possui ','Não possui ','600 x 2400 dpi, 200 lpi','800.000 impressões','PCL: Adobe® PostScript® 3:','frente e verso automático','Windows / Linux / Mac ','Não informado','Não informado','3,9 Segundos','Até 600 x 600 dpi','Não informado','Não informado','Até 120 ipm','Não informado','Até 600 x 600 dpi','Digitalizar para SMB, Digitalizar para FTP, Digitalizar para USB, Digitalizar para E-mail, Digitalizar para DocBox','Não informado','Não informado','Statement até 279,4 mm x 431,8 mm','Duplex','300 Folhas','4.000 folhas (80 g/m2) / 2 Bandejas de Volume: 1.500 folhas','(Módulo de Entrada de Papel Externo) (Opcional) Bandeja 1 e 2: 600 folhas, Bandeja 3 e 4: 1.700 folhas / 4.600 Folhas','Não informado','250 folhas','Máximo: 320 mm x 487 mm','50 g/m2 a 300 g/m2','50 g/m2 a 300 g/m2',0,1,1,'', '');

INSERT INTO planilhao.planilhao_multifuncional_producao
(uploaded_at,fabricante,modelo,tecnologia_de_impressao,velocidade_de_impressao,processador,memoria_minima,disco_rigido,interface_padrao,interface_opcional,interface_wireless,resolucao_de_impressao,ciclo_mensal,linguagem_de_impressao,frente_e_verso_automatico,sistema_operacional,painel,velocidade_de_copia,tempo_de_primeira_pagina,resolucao_de_copia,ampliacao_e_reducao,copias_multiplas,velocidade_de_digitacao,compatibilidade,resolucao,destino_de_saida,formatos_de_saida,tamanho_do_vidro,tamanho_do_adf,tipo_da_passagem_do_adf,capacidade_de_folhas_no_adf,bandeja_de_entrada_de_papel,capacidade_maxima_de_bandejas,bandeja_multiuso,bandeja_de_saida,suporta_tamanho,gramatura_na_bandeja_principal,gramatura_na_bandeja_multiuso,colorida,a4,a3,foto,catalogo)
VALUES('2020-08-26 13:31:08','Konica ','Konica bizhub PRESS 1250','Laser','125 ppm A4','2,8 Ghz - controladora','2 GB - controladora','250 - controladora','USB 2.0 - USB ','Não possui ','Não possui ','1200 x 1200','3000000','PCL5E/XL (PCL6) Adobe Postscript (PS3019)','Padrão','Windows, Mac, Linux','Painel touch ','125 ppm A4','3 seg','200, 300, 400, 600, 1200','Informação não encontrada ','Informação não encontrada ','105 ppm','Twain','200, 300, 400, 600, 1200',' Scan-to-HD, Scan-to-FTP, Scan-to-Email, Scan-to-SMB','Informação não encontrada ','A3 ','A3 ','Passagem única ','100 folhas','3 Bandejas de 1.000 folhas','3 Gavetas 6.000 folhas','Informação não encontrada ','4.200 folhas Opcional','A5 até o A3+','40 - 350 g/m²','40 - 350 g/m²',0,1,1,'', '');

INSERT INTO planilhao.planilhao_multifuncional_producao
(uploaded_at,fabricante,modelo,tecnologia_de_impressao,velocidade_de_impressao,processador,memoria_minima,disco_rigido,interface_padrao,interface_opcional,interface_wireless,resolucao_de_impressao,ciclo_mensal,linguagem_de_impressao,frente_e_verso_automatico,sistema_operacional,painel,velocidade_de_copia,tempo_de_primeira_pagina,resolucao_de_copia,ampliacao_e_reducao,copias_multiplas,velocidade_de_digitacao,compatibilidade,resolucao,destino_de_saida,formatos_de_saida,tamanho_do_vidro,tamanho_do_adf,tipo_da_passagem_do_adf,capacidade_de_folhas_no_adf,bandeja_de_entrada_de_papel,capacidade_maxima_de_bandejas,bandeja_multiuso,bandeja_de_saida,suporta_tamanho,gramatura_na_bandeja_principal,gramatura_na_bandeja_multiuso,colorida,a4,a3,foto,catalogo)
VALUES('2020-08-26 13:31:09','Xerox®','Xerox® D136','Não informado','136 ppm – A4','Não informado','2 GB RAM - Servidor de Cópia/Impressão Integrado (Standard)','320 GB - Servidor de Cópia/Impressão Integrado (Standard)','Interface Ethernet (10 MBTX/seg e 100 MBTX/seg e 1000MBTX/seg (opcional)) - Servidor de Cópia/Impressão Integrado (Standard)','Não possui ','Não possui ','Resolução da rasterização até 1200 x 1200 dpi e resolução até 2400 x 2400 dpi ',' 2.000.000 páginas por mês','Adobe® PostScript® 3™
• PDF
• PCL® 5e e 6
• TIFF
• HP-GL, HP-GL2 - Servidor de Cópia/Impressão Standard','Impressão de uma ou duas faces','Windows / Mac OS / Citrix /  Driver personalizado para Unix: / Oracle Solaris / Linux /  Red Hat / Certificação Citrix e WHQL - Servidor de Cópia/Impressão Standard','Ecrã tátil planos a cores de 10,4 polegadas - Servidor de Cópia/Impressão Standard','A4 lateral: 136 folhas/min.','3,7 segundos ou menos','600 × 600 dpi ','Ampliação
1:1±0.7% 1:1.154,1:1.225,1:1.414,1:1.632, 1:2.000
% Variável: 1:0,25 a 1:4,00 (em incrementos de 1%)
Ampliação fixa
1:0.250, 1:0.500, 1:0.612, 1:0.707, 1:0.816, 1:0.866,1:1.154, 1:1.225,
1:1.414, 1:1.632, 1:2.000, 1:4.000
Ampliação arbitrária
1:0,25-1:4,00 (em incrementos de 1%)','9.999 folhas','200 ipm
a preto e branco, simplex / duplex','TWAIN','600 x 600 dpi','Scan to Email com notificação de entrega de e-mail
• Scan to Network File Server
• Digitalizar/Gravar para USB','PDF, JPEG, TIFF ou TIFF de várias páginas; suporta LDAP','A5 a A3','A5 a A3','Alimentador automático de documentos duplex ','250 folhas','Bandeja 1: 1 100 folhas / • Bandeja 2 : 1 600 folhas / Bandeja 3-4: 550 folhas cada','Alimentador Opcional de Alta Capacidade:
2 bandejas, 2000 folhas cada / Alimentador Opcional de Alta Capacidade com
2 bandejas para formatos maiores: 4000 folhas','250 folhas',' Capacidade do empilhador: 3000 folhas','5,5 x 7,2 pol./140 mm
x 182 mm (A5) até um máximo de 13 x 19,2 pol./ 330 mm x 488 mm (SRA3)','52 g/m² a 216 g/m²','52 a 253 g/m2',0,1,1,'', '');

INSERT INTO planilhao.planilhao_multifuncional_producao
(uploaded_at,fabricante,modelo,tecnologia_de_impressao,velocidade_de_impressao,processador,memoria_minima,disco_rigido,interface_padrao,interface_opcional,interface_wireless,resolucao_de_impressao,ciclo_mensal,linguagem_de_impressao,frente_e_verso_automatico,sistema_operacional,painel,velocidade_de_copia,tempo_de_primeira_pagina,resolucao_de_copia,ampliacao_e_reducao,copias_multiplas,velocidade_de_digitacao,compatibilidade,resolucao,destino_de_saida,formatos_de_saida,tamanho_do_vidro,tamanho_do_adf,tipo_da_passagem_do_adf,capacidade_de_folhas_no_adf,bandeja_de_entrada_de_papel,capacidade_maxima_de_bandejas,bandeja_multiuso,bandeja_de_saida,suporta_tamanho,gramatura_na_bandeja_principal,gramatura_na_bandeja_multiuso,colorida,a4,a3,foto,catalogo)
VALUES('2020-08-26 13:31:10','Xerox ','Xerox PrimeLink B9136','Não informado','136 ppm – 8,5 x 11 pol. (A4)','Dual Core de 1,6 GHz - Servidor integrado Xerox','RAM de 4 GB - Servidor integrado Xerox','Disco rígido de 320 GB ou mais com 14,6 GB para armazenamento de documentos','10/100/1000 MB/s padrão - Servidor integrado Xerox','Não possui ','Não possui ','Resolução RIP de até 1200 x 1200 dpi e resolução de impressão de até 2400 x 2400 dpi','3,0 milhões de páginas','PDF, XPS®, PCL® 6, HP-GL2 (envio direto),
TIFF, JPEG
• Adobe® PostScript® 3™ - Servidor integrado Xerox','Impressão só frente ou frente e verso','Windows / Mac OS / Unix e Linux / Citrix / Novell - Servidor integrado Xerox','Visor do painel plano com tela de seleção por toque colorida de 10,4 pol - Servidor integrado Xerox','A4: 210 x 297 mm; A: 8,5 x 11 pol.: 1 Face: 136 ppm','3,5 segundos ou menos','600 x 600 dpi, 400 x 400 dpi, 300 x 300 dpi, 200 x 200 dpi','100%: 1:1 ± 0,7%
%de Pré-ajuste: 1:0,500, 1:0,707, 1:0,816, 1:0,866, 1:1,154,1:1,225,
1:1,414, 1:1,632, 1:2,000
%variável: 1:0,25 a 1:4,00 em incrementos de 1%','9999 folhas','270 ipm em preto e branco e/ou em cores, só frente/frente e verso','TWAIN - Servidor integrado Xerox','600 x 600 dpi','Digitalizar para E-mail, com notificação de entrega de e-mail
• Digitalizar para Servidor de arquivos de rede','PDF, JPEG, TIFF ou TIFF de várias páginas; suporta LDAP','Mínimo: A5 / Máximo: A3','Não informado','Alimentador automático de originais em frente e verso de única passagem','250 folhas','Bandeja 1: 1.100 folhas / Bandeja 2: 1.600 folhas / Bandeja 3-4: 550 folhas cada','Alimentador de alta capacidade opcional: Duas bandejas, 4.000 folhas / Alimentador de alta capacidade superdimensionado de duas bandejas opcional (não disponível com a Xerox® B9100): 4.000 folhas','250 folhas','Não informado','A3: A4: A5:','52 - 216 g/m²','52 a 350 g/m²',0,1,1,'', '');

INSERT INTO planilhao.planilhao_multifuncional_producao
(uploaded_at,fabricante,modelo,tecnologia_de_impressao,velocidade_de_impressao,processador,memoria_minima,disco_rigido,interface_padrao,interface_opcional,interface_wireless,resolucao_de_impressao,ciclo_mensal,linguagem_de_impressao,frente_e_verso_automatico,sistema_operacional,painel,velocidade_de_copia,tempo_de_primeira_pagina,resolucao_de_copia,ampliacao_e_reducao,copias_multiplas,velocidade_de_digitacao,compatibilidade,resolucao,destino_de_saida,formatos_de_saida,tamanho_do_vidro,tamanho_do_adf,tipo_da_passagem_do_adf,capacidade_de_folhas_no_adf,bandeja_de_entrada_de_papel,capacidade_maxima_de_bandejas,bandeja_multiuso,bandeja_de_saida,suporta_tamanho,gramatura_na_bandeja_principal,gramatura_na_bandeja_multiuso,colorida,a4,a3,foto,catalogo)
VALUES('2020-08-26 13:31:11','Ricoh ','Ricoh Pro 8320s','Laser','136 ppm','1.91 GHz','2 GB','640 GB','Ethernet (1000BASE-T/100BASE-TX/10Base-T); USB 2.0','IEEE802.11a/b/g/n, Bluetooth','IEEE802.11a/b/g/n','VCSEL: 2400 x 4800 dpi
Impressão: 1200 x 1200 dpi','1000K','PCL 5e, PCL 6, PDF, JPEG, TIFF
PDL Opcional Adobe PostScript 3, IPDS','frente e o verso','Windows, Mac OS X 10.11 ou
posterior, NetWare 6.5, UNIX Sun Solaris 10, HP-UX 11.x/11i v2/11i v3, SCO OpenServer 5.0.7/6.0, RedHat Linux','Painel de Operação Inteligente Sensível ao Toque, Colorido, de 17 ','136 ppm','4,6 segundos','VCSEL: 2400 × 4800 ppp
Cópia: 1200 × 1200 ppp','Auto Redução/Ampliação','Não informado','Simplex: 120 ipm; Duplex: 220 ipm','TWAIN','100/150/200/300/400/600 dpi','Digitalizar para USB/SD, Digitalizar para Email/Pasta/SMB/FTP/ URL
/PDF/A','Página Única: TIFF/JPEG/PDF/PDF de Alta
Compressão Diversas Páginas: TIFF/PDF/PDF de Alta
Compressão','297 × 432 mm','Não informado','digitalização duplex colorida, em passada única','220 folhas','Bandeja 1: 2200 folhas (1100 × 2)
Bandejas 2 e 3: 1100 folhas (550 × 2)','Capacidade máxima de papel de 12.600 folhas','Opcional Bandeja de Alimentação Manual BY5020 - 500 folhas','Não informado','Carta, A5/meio-Carta (140 x 216 mm) a 330 x 457 mm','52 a 256 g/m²','52 a 216 g/m²',0,1,1,'', '');

INSERT INTO planilhao.planilhao_multifuncional_producao
(uploaded_at,fabricante,modelo,tecnologia_de_impressao,velocidade_de_impressao,processador,memoria_minima,disco_rigido,interface_padrao,interface_opcional,interface_wireless,resolucao_de_impressao,ciclo_mensal,linguagem_de_impressao,frente_e_verso_automatico,sistema_operacional,painel,velocidade_de_copia,tempo_de_primeira_pagina,resolucao_de_copia,ampliacao_e_reducao,copias_multiplas,velocidade_de_digitacao,compatibilidade,resolucao,destino_de_saida,formatos_de_saida,tamanho_do_vidro,tamanho_do_adf,tipo_da_passagem_do_adf,capacidade_de_folhas_no_adf,bandeja_de_entrada_de_papel,capacidade_maxima_de_bandejas,bandeja_multiuso,bandeja_de_saida,suporta_tamanho,gramatura_na_bandeja_principal,gramatura_na_bandeja_multiuso,colorida,a4,a3,foto,catalogo)
VALUES('2020-08-26 13:31:12','Canon ','Canon varioPRINT 140','DirectPress','Velocidade de impressão máxima (ipm/ppm): 140 (A4/Carta)','2,7 GHz','4 GB','500 GB','Não informado','Não possui ','Não possui ','600 x 2400 dpi, 200 lpi','800.000 impressões','PCL: Adobe® PostScript® 3:','frente e verso automático','Windows / Linux / Mac ','Não informado','Não informado','3,9 Segundos','Até 600 x 600 dpi','Não informado','Não informado','Até 120 ipm','Não informado','Até 600 x 600 dpi','Digitalizar para SMB, Digitalizar para FTP, Digitalizar para USB, Digitalizar para E-mail, Digitalizar para DocBox','Não informado','Não informado','Statement até 279,4 mm x 431,8 mm','Duplex','300 Folhas','4.000 folhas (80 g/m2) / 2 Bandejas de Volume: 1.500 folhas','(Módulo de Entrada de Papel Externo) (Opcional) Bandeja 1 e 2: 600 folhas, Bandeja 3 e 4: 1.700 folhas / 4.600 Folhas','Não informado','250 folhas','Máximo: 320 mm x 487 mm','50 g/m2 a 300 g/m2','50 g/m2 a 300 g/m2',0,1,1,'', '');

INSERT INTO planilhao.planilhao_multifuncional_producao
(uploaded_at,fabricante,modelo,tecnologia_de_impressao,velocidade_de_impressao,processador,memoria_minima,disco_rigido,interface_padrao,interface_opcional,interface_wireless,resolucao_de_impressao,ciclo_mensal,linguagem_de_impressao,frente_e_verso_automatico,sistema_operacional,painel,velocidade_de_copia,tempo_de_primeira_pagina,resolucao_de_copia,ampliacao_e_reducao,copias_multiplas,velocidade_de_digitacao,compatibilidade,resolucao,destino_de_saida,formatos_de_saida,tamanho_do_vidro,tamanho_do_adf,tipo_da_passagem_do_adf,capacidade_de_folhas_no_adf,bandeja_de_entrada_de_papel,capacidade_maxima_de_bandejas,bandeja_multiuso,bandeja_de_saida,suporta_tamanho,gramatura_na_bandeja_principal,gramatura_na_bandeja_multiuso,colorida,a4,a3,foto,catalogo)
VALUES('2020-08-26 13:31:13','Konica ','Konica AccurioPress 6135','Não informado','A4/8.5x11 - 136 ppm / A3 - 78 ppm
1x17- 76 ppm','2.9GHz - CONTROLADOR','16GB - CONTROLADOR','1TBx2,SSD:4 GB - CONTROLADOR','10/100/1000Base -T, USB3.0host','Não possui ','Não possui ','1.200 x 1.200 dpi','Não informado','PCL5SE/XL(PCL6) / Adobe PostScript3(PS3020) / Impressão direta dePDF
(PDF Ver.1.7) / Impressão direta De TIFF (cumple con TIFF Ver. 6) / PPML
(Ver. 2.2) / APPE 4.2 (con UK-217)
Controladora de impressora: PCL6, PS PPD, Módulo para PS - CONTROLADOR','Não informado','Windows Server 2008, 2008R2, 2012, 2012R2, 2016
Windows 7,8,1,10 Xinclui 64bits / PS PPD / Windows Server 2008, 2008R2,
2012, 2012R2, 2016 / Windows 7, 8,1, 10 »Xinclui 64bits /
Módulo para PS: Windows Server 2008, 2008R2, 2012, 2012R2, 2016 /
Windows 7,8,1,10 Xinclui 64bits / Mac os X 10,8, 10,9, 10,10, 10,11,10,12 - CONTROLADOR','painel de operacão','Não informado','2.7 seg ou menos','Resolução - 600 x 600 dpi','Zoom - 25 - 400% (0.1% +)','Não informado','Tamanho simples: 120 opm, imagem meramente ilustrativa Lateral: 240 opm','Não informado','Não informado','Não informado','Não informado','297mm x 431.8 mm','Não informado','Não informado','Não informado','Não informado','Não informado','Não informado','Não informado','182mm x 139mm = 324mm x 463mm','40 ~ 300 g/m²','Não informado',0,1,1,'', '');

